export const PROMO_INVALID = "PROMO_INVALID";
export const PROMO_EXPIRED = "PROMO_EXPIRED";
export const PROMO_MAX_REDEMPTIONS = "PROMO_MAX_REDEMPTIONS";
export const PROMO_ALREADY_USED = "PROMO_ALREADY_USED";
export const PROMO_NOT_FIRST_PAID = "PROMO_NOT_FIRST_PAID";
export const PROMO_INCREASE_NOT_ELIGIBLE = "PROMO_INCREASE_NOT_ELIGIBLE";
